<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\Mods\TrickTweakGuard.cs" Link="TrickTweakGuard.cs" />
    <Compile Include="..\..\Mods\HangFiveControl.cs" Link="HangFiveControl.cs" />
  </ItemGroup>
</Project>
