<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\Mods\LateNativeHooks.cs" Link="LateNativeHooks.cs" />
    <Compile Include="..\..\Mods\CustomHairRenderPolicyPatch.cs" Link="CustomHairRenderPolicyPatch.cs" />
  </ItemGroup>
</Project>
